### ISSUE TITLE
Run this source code in local

### ISSUE THREAD

**Issue by superstar1205** [ocventures/Social-Media-Platform#3]
![image](https://user-images.githubusercontent.com/86986628/186370391-66bdea8a-0da4-4cf0-8acf-80cb21c6d496.png)

I run your script in my local.

**Comment by ProDev-Web** [comment]
And now I'm waiting for your reply.

**Comment by IGener8** [comment]
Cool how does it work functionality wise? I built it a few years ago but I just want to get it back to the point where it's functional so I can better design from there.

**Comment by ProDev-Web** [comment]
Yes of course, I can redesign too.

**Comment by IGener8** [comment]
What server would you recommend running this on?

**Comment by ProDev-Web** [comment]
Now I'm run your script in local (XAMPP).
but for hosting, I prefer cPanel that provide hosting service like HostGator, Bluehost...

**Comment by IGener8** [comment]
Yeah cool, I have a spare bluehost server ready to go. Is it possible to link a .au domain to a platform hosted on bluehost?

**Comment by ProDev-Web** [comment]
Yes, You can.

**Comment by IGener8** [comment]
Cool I own searchengineoptimisation.net.au and will look to set the demo platform up on that for the time being

**Comment by ProDev-Web** [comment]
Okay, and what is your current job?

**Comment by IGener8** [comment]
I do seo and own a company that does that for clients. I do some stuff with crytpo as well. How about you?

**Comment by ProDev-Web** [comment]
I'm a full-stack developer.

**Comment by IGener8** [comment]
Cool, would you be open to assist with web development for client websites? I am looking to move away from that part of the business and will need someone to fill that spot when the work arises.

**Comment by ProDev-Web** [comment]
yes of course. That's my major.

**Comment by ProDev-Web** [comment]
and that's long-term project or short-term project.

**Comment by IGener8** [comment]
Cool. I have just started marketing so will hopefully get a few coming through over the next month or two.

The platform I am looking to host will hopefully be long term. I am not sure where I want to take it yet. It will be centered around creating a digital marketing forum. Similar to a sub redit. Just without all the other subreddits. In essence to discuss updates in the web development, seo and digital marketing world.

**Comment by IGener8** [comment]
I want to use the platform to build domain authority for my main business as well as find way to monetize the platform ect.

**Comment by ProDev-Web** [comment]
Good, I have already worked on marketing website development project as a designer & frontend developer.

**Comment by ProDev-Web** [comment]
> I want to use the platform to build domain authority for my main business as well as find way to monetize the platform ect.

Can you explain about this more detail?

**Comment by IGener8** [comment]
I will send it all through via email tomorrow.

**Comment by ProDev-Web** [comment]
OK, I'll wait.
Have a good day! :)

**Comment by IGener8** [comment]
@ProDev-Web what is your email address again?

**Comment by ProDev-Web** [comment]
How are you?
here is my email address
`devking1205@gmail.com`
[Telegram](https://t.me/ProDev1205)

**Comment by IGener8** [comment]
I am well, how are you going today? Thanks - I have just shared a document I am doing up for the project

**Comment by ProDev-Web** [comment]
Hi, How are you?

**Comment by ProDev-Web** [comment]
Now, I'm waiting your reply.

**Comment by ProDev-Web** [comment]
Hi, Do you have any problem?

**Comment by ProDev-Web** [comment]
your trust....

**Comment by IGener8** [comment]
Hey mate sorry, I've been away this week. I'll be back tomorrow and will get back to you.

**Comment by ProDev-Web** [comment]
OK. I'll wait.

**Comment by ProDev-Web** [comment]
> Hey mate sorry, I've been away this week. I'll be back tomorrow and will get back to you.

Already passed and started new week.

**Comment by ProDev-Web** [comment]
Don't disappoints me... (your trust score go to low... 👎🏼)

**Comment by IGener8** [comment]
I will contact you when I am ready to proceed. We have a few changes happening atm. We will be looking to get started on the platform in a few weeks. You can join our discord to stay in close contact.

**Comment by ProDev-Web** [comment]
Thanks for your reply.
My Discord name: Destiny98#7450
You can invite me.

**Comment by IGener8** [comment]
I have sent you a request

**Comment by ProDev-Web** [comment]
Unfortunately, My discord disabled. :(
